const START_GAME = 'START_GAME';
const ADD_COLOR = 'ADD_COLOR';
const DISPLAY_COLORS = 'DISPLAY_COLORS';
const PLAYER_GUESSED_RIGHT = 'PLAYER_GUESSED_RIGHT';
const PLAYER_GUESSED_RIGHT_LAST_COLOR = 'PLAYER_GUESSED_RIGHT_LAST_COLOR';
const PLAYER_GUESSED_RIGHT_STILL_PLAYING = 'PLAYER_GUESSED_RIGHT_STILL_PLAYING';
const PLAYER_GUESSED_WRONG = 'PLAYER_GUESSED_WRONG';
const SAVE_STATE = 'SAVE_STATE';
const QUIT_AND_SAVE = 'QUIT_AND_SAVE';
export {
    START_GAME,
    ADD_COLOR,
    DISPLAY_COLORS,
    PLAYER_GUESSED_RIGHT,
    PLAYER_GUESSED_RIGHT_LAST_COLOR,
    PLAYER_GUESSED_RIGHT_STILL_PLAYING,
    PLAYER_GUESSED_WRONG, SAVE_STATE,QUIT_AND_SAVE
};